blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Recovery-Compass/compass-outlaw/tree/main/docs
    about: Check our documentation for guides and resources
  - name: Discussions
    url: https://github.com/Recovery-Compass/compass-outlaw/discussions
    about: Ask questions and discuss ideas with the community
